USE NTT
CREATE DATABASE QLBH_1
ON PRIMARY
( NAME = 'QuanlyBH', FILENAME = 'D:\BTSQL\QuanlyBH.mdf' , SIZE = 4048KB , MAXSIZE =
10240KB , FILEGROWTH = 20%)
LOG ON
( NAME = 'QLBH_log', FILENAME = 'D:\BTSQL\QLBH_log.ldf' , SIZE = 1024KB , MAXSIZE =
10240KB , FILEGROWTH = 10%)
USE NTT
CREATE TABLE NhomSanPham
(	MaNhom INT PRIMARY KEY NOT NULL, 
	TenNhom NVARCHAR(15) NULL)
CREATE TABLE SanPham
(	MaSp INT PRIMARY KEY NOT NULL, 
	TenSp NVARCHAR(40) NOT NULL,
	Donvitinh NVARCHAR(20) NULL, 
	GiaGoc MONEY NULL, 
	SLTON INT NULL,
	MaNhom INT NULL, 
	MaNCC INT NULL, 
	MoTa NVARCHAR(50) NULL)
CREATE TABLE HoaDon
(	MaHD INT PRIMARY KEY NOT NULL,
	NgayLapHD DATETIME NULL,
	MaKh NCHAR(5) NULL,
	NgayGiao DATETIME NULL,
	Noichuyen NVARCHAR(60) NOT NULL,
	MaNV INT NULL)
CREATE TABLE CT_HoaDon
(	MaHD INT NOT NULL,
	MaSp INT NOT NULL,
	Dongia MONEY NULL,
	Soluong SMALLINT NULL,
	ChietKhau MONEY NULL,
PRIMARY KEY CLUSTERED
(
 [MaHD] ASC,
 [MaSp] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, 
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) 
ON [PRIMARY]
CREATE TABLE NhaCungCap
(	MaNCC INT PRIMARY KEY NOT NULL, 
	TenNcc NVARCHAR(40) NOT NULL, 
	Diachi NVARCHAR(60) NULL, 
	Phone NVARCHAR(24) NULL, 
	SoFax NVARCHAR(24) NULL, 
	DCMail NVARCHAR(50)NULL)
CREATE TABLE KhachHang
(	MaKH NCHAR(5) PRIMARY KEY NOT NULL, 
	TenKh NVARCHAR(40) NOT NULL,
	Diachi NVARCHAR(60) NULL, 
	Phone NVARCHAR(24) NULL,
	LoaiKh NVARCHAR(3) NULL,  
	SoFax NVARCHAR(24) NULL, 
	DCMail NVARCHAR(50) NULL, 
	DiemTL INT NULL)
CREATE TABLE NhanVien
(	MaNV INT PRIMARY KEY, 
	TenNV NVARCHAR(40) NOT NULL, 
	Diachi NVARCHAR(60) NULL, 
	Phone NVARCHAR(60) NULL)
ALTER TABLE HoaDon  WITH CHECK ADD FOREIGN KEY (MaKH) REFERENCES KhachHang (MaKh)
ALTER TABLE HoaDon  WITH CHECK ADD FOREIGN KEY (MaNV) REFERENCES NhanVien (MaNV)
ALTER TABLE CT_HoaDon  WITH CHECK ADD FOREIGN KEY (MaHD) REFERENCES HoaDon (MaHD)
ALTER TABLE CT_HoaDon WITH CHECK ADD FOREIGN KEY (MaSp) REFERENCES SanPham (MaSp)
ALTER TABLE SanPham WITH CHECK ADD FOREIGN KEY (MaNhom) REFERENCES NhomSanPham (MaNhom)
ALTER TABLE SanPham WITH CHECK ADD FOREIGN KEY (MaNCC) REFERENCES NhaCungCap (MaNCC)
ALTER TABLE SanPham WITH CHECK ADD CONSTRAINT [SP_CK_1] CHECK (([Giagoc]>(0)))
ALTER TABLE SanPham CHECK CONSTRAINT [SP_CK_1]
ALTER TABLE SanPham WITH CHECK ADD CONSTRAINT [SP_CK_2] CHECK (([SLTON]>(0)))
ALTER TABLE SanPham CHECK CONSTRAINT [SP_CK_2]
ALTER TABLE HoaDon WITH CHECK ADD CONSTRAINT [HD_CK] CHECK (([NgayLapHD]>= GETDATE()))
ALTER TABLE HoaDon CHECK CONSTRAINT [HD_CK]
ALTER TABLE CT_HoaDon WITH CHECK ADD CONSTRAINT [CTHD_CK_1] CHECK (([Soluong]>(0)))
ALTER TABLE CT_HoaDon CHECK CONSTRAINT [CTHD_CK_1]
ALTER TABLE CT_HoaDon WITH CHECK ADD CONSTRAINT [CTHD_CK_2] CHECK (([ChietKhau]>(0)))
ALTER TABLE CT_HoaDon CHECK CONSTRAINT [CTHD_CK_2]
ALTER TABLE KhachHang WITH CHECK ADD CONSTRAINT [KH_CK_1] CHECK (([LoaiKh]='VIP' OR [LoaiKh]='TV' OR [LoaiKh]='VL'))
ALTER TABLE KhachHang CHECK CONSTRAINT [KH_CK_1]  
ALTER TABLE KhachHang WITH CHECK ADD CONSTRAINT [KH_CK_2] CHECK (([DiemTL]>=(0)))
ALTER TABLE HoaDon ADD LoaiHD CHAR(1)
ALTER TABLE HoaDon WITH CHECK ADD CONSTRAINT [CT_HoaDon_CK_3] CHECK (([LoaiHD]='N' OR [LoaiHD]='X' OR [LoaiHD]='C'))
ALTER TABLE HoaDon WITH CHECK ADD CONSTRAINT [DF_HoaDon_LoaiHD] DEFAULT 'N' FOR LoaiHD
ALTER TABLE HoaDon ADD CONSTRAINT [HD_CK_3] CHECK (([NgayGiao]>=[NgayLapHD]))